#!/usr/bin/env python3
"""Embed a TensorFlow.js Layers model into the userscript.

The generated userscript contains the model topology and shard bytes, so it
does not need to fetch model files at runtime. TensorFlow.js itself remains a
normal userscript dependency loaded by the manager's @require directive.
"""

from __future__ import annotations

import argparse
import base64
import copy
import json
import re
from pathlib import Path


BEGIN_MARKER = "    // BEGIN EMBEDDED MODEL"
END_MARKER = "    // END EMBEDDED MODEL"
DEFAULT_REVISION = "bce4a5c51480356bbdfc0d4d853d1ff9a383420d"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model_dir", type=Path, help="Directory containing model.json and shards")
    parser.add_argument(
        "--userscript",
        type=Path,
        default=Path("predict.user.js"),
        help="Userscript template and output path",
    )
    parser.add_argument(
        "--revision",
        default=DEFAULT_REVISION,
        help="Hub commit containing the source artifact",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=64 * 1024,
        help="Base64 chunk size in generated JavaScript",
    )
    return parser.parse_args()


def read_model(model_dir: Path) -> tuple[dict, list[dict], bytes]:
    model_json_path = model_dir / "model.json"
    model_json = json.loads(model_json_path.read_text(encoding="utf-8"))
    try:
        topology = model_json["modelTopology"]
        manifest = model_json["weightsManifest"]
    except KeyError as error:
        raise ValueError(f"Invalid TensorFlow.js model.json: missing {error.args[0]}") from error

    weight_specs = [
        spec
        for group in manifest
        for spec in group.get("weights", [])
    ]
    shard_paths = [
        path
        for group in manifest
        for path in group.get("paths", [])
    ]
    if not weight_specs or not shard_paths:
        raise ValueError("TensorFlow.js model has no weights")

    weight_data = b"".join(
        (model_dir / path).read_bytes()
        for path in shard_paths
    )
    return normalize_topology(topology), weight_specs, weight_data


def normalize_topology(topology: dict) -> dict:
    """Adapt Keras 3 topology fields to TensorFlow.js Layers format."""
    topology = copy.deepcopy(topology)
    model_config = topology.get("model_config")
    if not isinstance(model_config, dict):
        raise ValueError("Expected a Keras model_config in model topology")

    # Keras 3 calls this model type Functional; TFJS Layers calls it Model.
    if model_config.get("class_name") == "Functional":
        model_config["class_name"] = "Model"
    config = model_config.get("config", {})
    for key in ("input_layers", "output_layers"):
        value = config.get(key)
        if value and not isinstance(value[0], list):
            config[key] = [value]

    for layer in config.get("layers", []):
        layer_config = layer.get("config", {})
        if layer.get("class_name") == "InputLayer":
            if "batch_shape" in layer_config:
                layer_config["batchInputShape"] = layer_config.pop("batch_shape")
            # `optional` is a Keras 3-only field and is not understood by TFJS.
            layer_config.pop("optional", None)

        normalized_nodes = []
        for node in layer.get("inbound_nodes", []):
            connections = []
            for argument in node.get("args", []):
                history = argument.get("config", {}).get("keras_history")
                if not history or len(history) != 3:
                    raise ValueError(
                        f"Cannot normalize inbound node for layer {layer.get('name')}"
                    )
                connections.append([*history, {}])
            normalized_nodes.append(connections)
        layer["inbound_nodes"] = normalized_nodes
    return topology


def render_block(
    topology: dict,
    weight_specs: list[dict],
    weight_data: bytes,
    revision: str,
    chunk_size: int,
) -> str:
    if chunk_size <= 0:
        raise ValueError("chunk-size must be positive")

    encoded = base64.b64encode(weight_data).decode("ascii")
    chunks = [
        encoded[index:index + chunk_size]
        for index in range(0, len(encoded), chunk_size)
    ]
    chunk_source = ",\n".join(
        f"        {json.dumps(chunk)}" for chunk in chunks
    )
    topology_source = json.dumps(topology, ensure_ascii=True, separators=(",", ":"))
    specs_source = json.dumps(weight_specs, ensure_ascii=True, separators=(",", ":"))
    return "\n".join([
        BEGIN_MARKER,
        "    // Generated by scripts/embed_tfjs_model.py. Keep this block deterministic.",
        f"    const MODEL_REVISION = {json.dumps(revision)};",
        f"    const MODEL_TOPOLOGY = {topology_source};",
        f"    const MODEL_WEIGHT_SPECS = {specs_source};",
        "    const MODEL_WEIGHT_DATA_BASE64 = [",
        chunk_source,
        "    ].join('');",
        END_MARKER,
    ])


def embed_model(
    model_dir: Path,
    userscript_path: Path,
    revision: str,
    chunk_size: int,
) -> None:
    topology, weight_specs, weight_data = read_model(model_dir)
    source = userscript_path.read_text(encoding="utf-8")
    pattern = re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER)
    block = render_block(topology, weight_specs, weight_data, revision, chunk_size)
    updated, replacements = re.subn(pattern, block, source, count=1, flags=re.DOTALL)
    if replacements != 1:
        raise ValueError(
            f"Expected exactly one embedded-model block in {userscript_path}, got {replacements}"
        )
    userscript_path.write_text(updated, encoding="utf-8")
    print(
        f"Embedded {len(weight_data):,} weight bytes from {model_dir} "
        f"into {userscript_path} ({userscript_path.stat().st_size:,} source bytes)."
    )


def main() -> None:
    args = parse_args()
    embed_model(args.model_dir, args.userscript, args.revision, args.chunk_size)


if __name__ == "__main__":
    main()
